### ISSUE TITLE
Precision loss

### ISSUE THREAD

**Issue by Meiendorf** [NicolaiOnov/MaAssignment#1]
Добрый день.   
Меня зовут Роман, мы, совместно с @aandrey1993 проводим ревью тестового задания. 
По ходу ревью будем открывать тикеты с вопросами/предложениями для улучшения кода. 

## Описание
В файле заполнения базы тестовыми данными, первый и третий счета записываются с суммами и знаками после запятой:
![image](https://user-images.githubusercontent.com/31164055/116089323-65a71800-a6ab-11eb-95b4-6fc8876a01b3.png)

Если в колонке хранится сумма в центах, по идее, там не должно быть знаков после запятой.    
Из-за того, что в коде потом происходит деление на 100 для конвертации из центов, то для третьего счёта теряется значение: 
![image](https://user-images.githubusercontent.com/31164055/116089722-cc2c3600-a6ab-11eb-81d6-e21201f1d890.png)

Нужно или хранить только целые числа для сумм в центах, или переделать конвертацию, чтобы не обрезать значение.

**Comment by NicolaiOnov** [comment]
Добрый день, Роман. Спасибо что зашли на огонек.
По поводу вашего комментария. Это не баг, это фича. "Срезанные" копейки можно было бы пустить на нужды разработчиков :D 
Шучу конечно, ошибку я исправил, можете взглянуть на прикрепленный pull request

**Comment by Meiendorf** [comment]
Спасибо, вопрос закрыт)
