### ISSUE TITLE
No custom error messages

### ISSUE THREAD

**Issue by Meiendorf** [NicolaiOnov/MaAssignment#2]
Все exception's обрабатываются Sping и выведутся в логи, но их все равно можно отловить, чтобы создать сообщение об ошибке с настраиваемым текстом. Если знать ключевые слов логов, будет проще искать ошибки в больших файлах журнала. Например, в контроллере можно сделать что-то вроде:
```java
@GetMapping
    public ResponseEntity<List<AccountDto>> get() {
        try {
            return ResponseEntity.ok(accountsRepository
                    .readAllAccounts()
                    .stream().map(account -> dtoMapper.mapToDto(account))
                    .collect(Collectors.toList()));
        } catch (DataAccessException e) {
            String msg = "Could not get all customer accounts!";
            LOG.error(msg, e);
            return ResponseEntity.status(500).build();
        }
    }
```

**Comment by NicolaiOnov** [comment]
Да, в этом есть смысл :) Добавил изменения в прикрепленном pull request'е

**Comment by Meiendorf** [comment]
Спасибо, коллега отписал в pull request по поводу логгирования, закрываю тикет
