### ISSUE TITLE
Dependency Injection is not used

### ISSUE THREAD

**Issue by aandrey1993** [NicolaiOnov/MaAssignment#3]
Добрый день, меня зовут Андрей. Совместно с Романом, делаем ревью Вашего тестового задания. 

Хорошей практикой считается использования `Dependency Injection` при внедрении зависимостей. У Вас принцип инверсии зависимостей нарушен, так как `AccountsController` явно зависит от репозитария `AccountsRepository`.

Добавьте, пожалуйста, интерфейс описывающий `AccountsRepository` и используйте DI при внедрении его в `AccountsController`. (Аналогичная ситуация с сервисом `DtoMapper`)

Если возникнут какие-то вопросы, можете задавать их в комментариях.

**Comment by NicolaiOnov** [comment]
Добрый день, Андрей. Спасибо что зашли на огонек. 
Да, вы абсолютно правы. Достаточно нелепая ошибка с моей стороны :)
Сейчас поправим!

**Comment by NicolaiOnov** [comment]
Исправил! Изменения можете посмотреть в прикрепленном pull request'е

**Comment by aandrey1993** [comment]
Спасибо.  Так лучше ) 
Можно ещё дополнить аннотацией `@Autowired` при DI с помощью конструктора. При её использовании, Spring сам будет искать подходящий bin для определения интерфейса. Она не является обязательной, но с её помощью можно явно указать что иньекция выполняется через конструктор. (считается хорошей практикой)

В остальном вопрос закрыт )

**Comment by NicolaiOnov** [comment]
Спасибо за совет, nice to know
Добавил аннотацию.
